services:
  message_broker_rabbitmq:
    env_file:
      - .env
    image: rabbitmq:latest
    container_name: soft.rabbitmq
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions '/etc/rabbitmq/definitions.json'"
    ports:
      - "5672:5672"
      - "15672:15672"