spring:
  application:
    name: Task Management System

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs


  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

custom:
  verify:
    code:
      lifetime: 15
  databaseService:
    url: http://localhost:8432/api
  mailService:
    exchange:
      verification: verificationExchange
      notification: notificationExchange
    queue:
      verification: verificationQueue
      notification: notificationQueue
    routingKey:
      verification: verificationRoutingKey
      notification: notificationRoutingKey
server:
  port: 8080
